### ISSUE TITLE
WebPart error after upgrade to 4.2

### ISSUE THREAD

**Issue by benoitfournier** [pnp/custom-learning-office-365#504]
I updated the solution to 4.2 and now I get errors on all the pages. 

[SPLoaderError.loadComponentError]:
Failed to load component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Failed to load URL 'https://xxxx.sharepoint.com/sites/CatalogueApplicatif365/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_fr-fr_f7f1a36c1c8cdbf856a14bc6f5489387.js' for resource 'M365LPStrings' in component '141d4ab7-b6ca-4bf4-ac59-25b7bf93642d' (CustomLearningWebPart). The file was not found in the server.

INNERERROR:
Failed to load URL 'https://xxxx.sharepoint.com/sites/CatalogueApplicatif365/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_fr-fr_f7f1a36c1c8cdbf856a14bc6f5489387.js' for resource 'M365LPStrings' in component '141d4ab7-b6ca-4bf4-ac59-25b7bf93642d' (CustomLearningWebPart). The file was not found in the server.
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr_ac1647cbfaf2210d5e002fba1a3a8e26.js:65:19890)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr_ac1647cbfaf2210d5e002fba1a3a8e26.js:65:118417)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr_ac1647cbfaf2210d5e002fba1a3a8e26.js:65:156201)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr_ac1647cbfaf2210d5e002fba1a3a8e26.js:65:152246)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_fr-fr_b0f71b5278af14e6a9ab.js:1:11895

**Comment by benoitfournier** [comment]
Found the problem. I uploaded the solution with a different .sppkg name. When I deleted the duplicate file from the app catalog, it revoved resources folder.

Re-uploaded and the issue is fixed.

My error, sorry
